package com.example.glsurfaceviewvodel.library_for_opengl.primitive.object2d

import com.example.glsurfaceviewvodel.library_for_opengl.primitive.MutableInterface
import com.example.glsurfaceviewvodel.library_for_opengl.primitive.RenderPrimitive

abstract class TwoDimensionalMutableFigure: RenderPrimitive(), MutableInterface